name: Bug Report
description: Report a reproducible problem
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug report. Please include enough detail to reproduce the issue.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-sentence description of the problem
      placeholder: Example - `--format html` fails when output path has spaces
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Exact steps and commands to reproduce
      placeholder: |
        1. Run...
        2. Run...
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: macOS 14.7 / Ubuntu 24.04 / Windows 11
    validations:
      required: true

  - type: input
    id: rust
    attributes:
      label: Rust version
      placeholder: rustc 1.78.0
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/output
      description: Paste error output, stack traces, or screenshots
      render: shell
